name: Run static checks and unit tests

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
    - main
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: 'go.mod'
    - name: Run unit tests
      run: make test
    - name: Build
      run: make
    - name: Build release binaries
      run: make release
